"""generated scenarios + session snapshot

Revision ID: 6789f18ae13c
Revises: f43855f82ab9
Create Date: 2026-06-01 00:43:16.833066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6789f18ae13c'
down_revision: Union[str, None] = 'f43855f82ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_scenarios',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('archetype', sa.String(length=40), nullable=False),
    sa.Column('scenario_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_scenarios_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.drop_column('scenario_json')

    with op.batch_alter_table('generated_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_scenarios_user_id'))

    op.drop_table('generated_scenarios')
    # ### end Alembic commands ###
