"""initial schema

Revision ID: f43855f82ab9
Revises: 
Create Date: 2026-05-31 00:46:45.137129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43855f82ab9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('drill_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('severity_start', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('objectives_met', sa.JSON(), nullable=False),
    sa.Column('escalation_timeline', sa.JSON(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('debriefs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('overall_grade', sa.String(length=4), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drill_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debriefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debriefs_session_id'), ['session_id'], unique=True)

    op.create_table('turns',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('user', 'persona', name='speaker', native_enum=False, length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=30), nullable=True),
    sa.Column('severity_after', sa.Integer(), nullable=True),
    sa.Column('confidence_after', sa.Integer(), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drill_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_session_id'))

    op.drop_table('turns')
    with op.batch_alter_table('debriefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debriefs_session_id'))

    op.drop_table('debriefs')
    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drill_sessions_user_id'))

    op.drop_table('drill_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
